Seems like it's probably important to close() the SoftSynthesizer -- something I missed earlier!
My hope is that not calling close() is what's been causing the app to crash on startup after some time debugging in the simulator with this exception, which I think could be expected if one calls open() too many times without ever calling close():

Process: com.kaelambda.note_grid, PID: 13529
java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
at android.media.AudioTrack.play(AudioTrack.java:2986)
at cn.sherlock.media.SourceDataLineImpl.start(SourceDataLineImpl.java:38)
at cn.sherlock.com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:940)
at com.kaelambda.note_grid.audio.MidiSoundController.<init>(MidiSoundController.kt:19)